/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs67proj;

import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author kernst
 */
public class CashPayment extends javax.swing.JFrame {

    private Reservation r;
    private Person p;
    public final DecimalFormat df = new DecimalFormat("#.00");
    private boolean isOneWay;
    private String dept;
    private String dest;
    private int adults;
    private int kids;
    private int bags;
    private double price;
    private Date expDate;
    private boolean isCommuter;
    
    /**
     * Creates new form CashPayment
     */
    public CashPayment() {
        initComponents();
    }
    
    public CashPayment(Reservation r, Person p, double price) {
        this.r = r;
        this.p = p;
        initComponents();
        
        this.isOneWay = r.getIsOneWay();
        this.isCommuter = r.getIsCommuter();
        if (isCommuter)
            Direction.setText("COMMUTER PASS");
        else if (isOneWay)
            Direction.setText("ONE WAY");
        else
            Direction.setText("ROUND TRIP");
        
        this.dept = r.getDept();
        Dept.setText(dept);
        
        this.dest = r.getDest();
        Dest.setText(dest);
        
        this.adults = r.getAdults();
        NumAdults.setText("" + adults);
        
        this.kids = r.getKids();
        NumKids.setText("" + kids);
        
        this.bags = r.getBags();
        NumBags.setText("" + bags);
        
        this.price = price;
        Total.setText("TOTAL: $" + df.format(price));
        
        this.expDate = r.getExpDate();
        Format formatter = new SimpleDateFormat("MM/dd/yyyy");
        String exp = formatter.format(expDate);
        Expiration.setText("" + exp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Total = new javax.swing.JLabel();
        SwipeNow = new javax.swing.JLabel();
        Direction = new javax.swing.JLabel();
        From = new javax.swing.JLabel();
        NumKids = new javax.swing.JLabel();
        Adults = new javax.swing.JLabel();
        Dept = new javax.swing.JLabel();
        NumAdults = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        Bags = new javax.swing.JLabel();
        Dest = new javax.swing.JLabel();
        NumBags = new javax.swing.JLabel();
        Kids = new javax.swing.JLabel();
        Expiration = new javax.swing.JLabel();
        ExpDate = new javax.swing.JLabel();
        Credit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        WrongPayment = new javax.swing.JLabel();
        SwipeNow1 = new javax.swing.JLabel();
        EmpIDSwiped = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Total.setFont(new java.awt.Font("Avenir Next Condensed", 1, 72)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("TOTAL: $00.00");

        SwipeNow.setFont(new java.awt.Font("Avenir Next Condensed", 2, 40)); // NOI18N
        SwipeNow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SwipeNow.setText("Please hand your payment to the");

        Direction.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Direction.setText("ONE WAY");

        From.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        From.setText("FROM:");

        NumKids.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NumKids.setText("0");

        Adults.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Adults.setText("ADULTS:");

        Dept.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Dept.setText("HANOVER");

        NumAdults.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NumAdults.setText("1");

        To.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        To.setText("TO:");

        Bags.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Bags.setText("BAGS:");

        Dest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Dest.setText("BOSTON: SOUTH STATION");

        NumBags.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NumBags.setText("0");

        Kids.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Kids.setText("CHILDREN:");

        Expiration.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Expiration.setText("12/17/1995");

        ExpDate.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        ExpDate.setText("EXPIRATION DATE:");

        Credit.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Credit.setText("PAY WITH CREDIT CARD INSTEAD");
        Credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        WrongPayment.setFont(new java.awt.Font("Avenir Next Condensed", 2, 18)); // NOI18N
        WrongPayment.setText("Chose the wrong payment method?");

        SwipeNow1.setFont(new java.awt.Font("Avenir Next Condensed", 2, 40)); // NOI18N
        SwipeNow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SwipeNow1.setText("Coach employee.");

        EmpIDSwiped.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        EmpIDSwiped.setText("FAKE SWIPE EMPLOYEE ID");
        EmpIDSwiped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIDSwipedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SwipeNow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SwipeNow, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(WrongPayment))
                                    .addComponent(Credit)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Bags)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NumBags))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Kids)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NumKids))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Adults)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NumAdults))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(To)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dest))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(From)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dept))
                                    .addComponent(Direction)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ExpDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Expiration)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmpIDSwiped)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adults, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumAdults, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kids, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumKids, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bags, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumBags, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Expiration, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(SwipeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SwipeNow1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(WrongPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpIDSwiped, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditActionPerformed
        dispose();
        CreditCardSwipe ticketFormCredit = new CreditCardSwipe(r, p, price);
        ticketFormCredit.setVisible(true);
    }//GEN-LAST:event_CreditActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        if (isOneWay && (dept.equals("NEW YORK CITY") || dest.equals("NEW YORK CITY"))) {
            FinalizeTicketInfoNYC ticketInfoNYC = new FinalizeTicketInfoNYC(r, p);
            ticketInfoNYC.setVisible(true);
        }
        else {
            FinalizeTicketInfo ticketInfo = new FinalizeTicketInfo(r, p);
            ticketInfo.setVisible(true);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void EmpIDSwipedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIDSwipedActionPerformed
        dispose();
        PaymentSuccess payScreen = new PaymentSuccess(r, p, price, false);
        payScreen.setVisible(true);
    }//GEN-LAST:event_EmpIDSwipedActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CashPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CashPayment().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adults;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Bags;
    private javax.swing.JButton Credit;
    private javax.swing.JLabel Dept;
    private javax.swing.JLabel Dest;
    private javax.swing.JLabel Direction;
    private javax.swing.JButton EmpIDSwiped;
    private javax.swing.JLabel ExpDate;
    private javax.swing.JLabel Expiration;
    private javax.swing.JLabel From;
    private javax.swing.JLabel Kids;
    private javax.swing.JLabel NumAdults;
    private javax.swing.JLabel NumBags;
    private javax.swing.JLabel NumKids;
    private javax.swing.JLabel SwipeNow;
    private javax.swing.JLabel SwipeNow1;
    private javax.swing.JLabel To;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel WrongPayment;
    // End of variables declaration//GEN-END:variables
}
