/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs67proj;

import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author kernst
 */
public class FinalizeCommuterPass extends javax.swing.JFrame {

    private Reservation r;
    private Person p;
    private int bags;
    private int adults;
    private int kids;
    private String dept;
    private String dest;
    private double price;
    private int paymentType; // -1 for not entered, 0 for credit, 1 for cash
    public final DecimalFormat df = new DecimalFormat("#0.00");
    private boolean isNewLondon;
    private boolean isLogan;
    private boolean isOneWay;
    private Date expDate;
    /**
     * Creates new form FinalizeCommuterPass
     */
    public FinalizeCommuterPass() {
        initComponents();
    }
    
    public FinalizeCommuterPass(Reservation r, Person p) {
        this.r = r;
        this.p = p;
        
        initComponents();
        
        this.isNewLondon = false;
        r.setIsOneWay(false);
        
        this.dept = r.getDept();
        if (dept.equals("NEW LONDON"))
            this.isNewLondon = true;
        From.setText("FROM: " + dept);
        
        this.dest = r.getDest();
        this.isLogan = false;
        if (dept.equals("BOSTON: LOGAN AIRPORT"))
            this.isLogan = true;
        To.setText("TO: " + dest);
        
        this.bags = r.getBags();
        this.adults = r.getAdults();
        this.kids = r.getKids();
        this.price = calcCost();
        this.paymentType = -1;
        
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DAY_OF_YEAR, 60);
        this.expDate = cal.getTime();
        Format formatter = new SimpleDateFormat("MM/dd/yyyy");
        String exp = formatter.format(expDate);
        r.setExpDate(expDate);
        Expiration.setText("EXPIRES: " + exp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoPassengers = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        AddPassengers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PaymentNotSet = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        SetPayment = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TripDetail = new javax.swing.JLabel();
        Direction = new javax.swing.JLabel();
        From = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Cash = new javax.swing.JButton();
        Credit = new javax.swing.JButton();
        AdultsLabel = new javax.swing.JLabel();
        NumAdults = new javax.swing.JSpinner();
        Back = new javax.swing.JButton();
        Submit2 = new javax.swing.JButton();
        Expiration = new javax.swing.JLabel();
        To = new javax.swing.JLabel();

        NoPassengers.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        NoPassengers.setBounds(new java.awt.Rectangle(100, 200, 400, 180));

        jLabel2.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("You entered 0 adults.");

        AddPassengers.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        AddPassengers.setText("ADD PASSENGERS");
        AddPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengersActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Please add at least one passenger to continue.");

        javax.swing.GroupLayout NoPassengersLayout = new javax.swing.GroupLayout(NoPassengers.getContentPane());
        NoPassengers.getContentPane().setLayout(NoPassengersLayout);
        NoPassengersLayout.setHorizontalGroup(
            NoPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoPassengersLayout.createSequentialGroup()
                .addGroup(NoPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NoPassengersLayout.createSequentialGroup()
                        .addGroup(NoPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NoPassengersLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(NoPassengersLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(AddPassengers)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NoPassengersLayout.setVerticalGroup(
            NoPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoPassengersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PaymentNotSet.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        PaymentNotSet.setBounds(new java.awt.Rectangle(100, 200, 400, 180));

        jLabel8.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel8.setText("You did not select a payment method.");

        SetPayment.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        SetPayment.setText("ADD PAYMENT METHOD");
        SetPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPaymentActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel9.setText("Please select \"CASH\" or \"CREDIT\" to continue.");

        javax.swing.GroupLayout PaymentNotSetLayout = new javax.swing.GroupLayout(PaymentNotSet.getContentPane());
        PaymentNotSet.getContentPane().setLayout(PaymentNotSetLayout);
        PaymentNotSetLayout.setHorizontalGroup(
            PaymentNotSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentNotSetLayout.createSequentialGroup()
                .addGroup(PaymentNotSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentNotSetLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9))
                    .addGroup(PaymentNotSetLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8))
                    .addGroup(PaymentNotSetLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(SetPayment)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PaymentNotSetLayout.setVerticalGroup(
            PaymentNotSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentNotSetLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SetPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TripDetail.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        TripDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TripDetail.setText("TRIP DETAIL:");

        Direction.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Direction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direction.setText("10 RIDE COMMUTER PASS");

        From.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        From.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        From.setText("FROM: HANOVER");

        Total.setFont(new java.awt.Font("Avenir Next Condensed", 1, 48)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("TOTAL: $0");

        Cash.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Cash.setText("CASH");
        Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashActionPerformed(evt);
            }
        });

        Credit.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Credit.setText("CREDIT");
        Credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditActionPerformed(evt);
            }
        });

        AdultsLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        AdultsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdultsLabel.setText("# OF ADULTS:");

        NumAdults.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NumAdults.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));
        NumAdults.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NumAdultsStateChanged(evt);
            }
        });

        Back.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Submit2.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Submit2.setText("SUBMIT");
        Submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2ActionPerformed(evt);
            }
        });

        Expiration.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Expiration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Expiration.setText("EXPIRES: 12/17/2017");

        To.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        To.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        To.setText("TO: BOSTON: SOUTH STATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(AdultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumAdults, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TripDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(From, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Direction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(To, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Expiration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(187, 187, 187))
                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(TripDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Expiration, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumAdults, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(618, 618, 618)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashActionPerformed
        paymentType = 1;
        Credit.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        Cash.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
    }//GEN-LAST:event_CashActionPerformed

    private void CreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditActionPerformed
        paymentType = 0;
        Credit.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
        Cash.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
    }//GEN-LAST:event_CreditActionPerformed

    private void NumAdultsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NumAdultsStateChanged
        adults = (Integer) NumAdults.getValue();
        r.setAdults(adults);
        calcCost();
    }//GEN-LAST:event_NumAdultsStateChanged

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        TicketInfo ticketScreen = new TicketInfo(p);
        ticketScreen.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void Submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2ActionPerformed
        if (adults == 0 || price == 0)
            NoPassengers.setVisible(true);
        else if (paymentType == -1)
            PaymentNotSet.setVisible(true);
        else {
            dispose();
        }
        if (paymentType == 0) {
            CreditCardSwipe ticketFormCredit = new CreditCardSwipe(r, p, price);
            ticketFormCredit.setVisible(true);
        }
        else if (paymentType == 1) {
            CashPayment ticketFormCash = new CashPayment(r, p, price);
            ticketFormCash.setVisible(true);
        }
    }//GEN-LAST:event_Submit2ActionPerformed

    private void AddPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengersActionPerformed
        NoPassengers.dispose();
    }//GEN-LAST:event_AddPassengersActionPerformed

    private void SetPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPaymentActionPerformed
        PaymentNotSet.dispose();
    }//GEN-LAST:event_SetPaymentActionPerformed

    public double calcCost() {
        double basePrice = 165.00;
        if (!isNewLondon && isLogan) {
            basePrice = 190.00;
        }
        else if (isNewLondon && !isLogan) {
            basePrice = 140.00;
        }
        else if (isNewLondon && isLogan) {
            basePrice = 165.00;
        }
        double totalPrice = adults * basePrice;
        
        price = totalPrice;
        Total.setText("TOTAL: $" + df.format(price));
        return price;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizeCommuterPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizeCommuterPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizeCommuterPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizeCommuterPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizeCommuterPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPassengers;
    private javax.swing.JLabel AdultsLabel;
    private javax.swing.JButton Back;
    private javax.swing.JButton Cash;
    private javax.swing.JButton Credit;
    private javax.swing.JLabel Direction;
    private javax.swing.JLabel Expiration;
    private javax.swing.JLabel From;
    private javax.swing.JFrame NoPassengers;
    private javax.swing.JSpinner NumAdults;
    private javax.swing.JFrame PaymentNotSet;
    private javax.swing.JButton SetPayment;
    private javax.swing.JButton Submit2;
    private javax.swing.JLabel To;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TripDetail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
