/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs67proj;

/**
 *
 * @author kernst
 */
public class HanLebNLTicketInfo extends javax.swing.JFrame {

    private String dept;
    private String dest;
    private boolean isOneWay;
    private Reservation r;
    private Person p;
    private boolean destSet;
    
    /**
     * Creates new form LeavingHanoverTicketInfo
     */
    public HanLebNLTicketInfo() {
        initComponents();
    }
    
    public HanLebNLTicketInfo(Reservation r, Person p) {
        this.r = r;
        this.p = p;
        this.dept = r.getDept();
        this.dest = r.getDest();
        this.isOneWay = r.getIsOneWay();
        this.destSet = false;
        
        initComponents();
        if (dept.equals("NEW LONDON")) {
            NYCDest.setVisible(false);
        }
        
        if (isOneWay) {
            OneWay.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
        }
        else {
            RoundTrip.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
        }
        
        HanoverLeave.setText(dept);
        HanoverLeave.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangeDept = new javax.swing.JFrame();
        LeavingFrom2 = new javax.swing.JLabel();
        HanoverLeave1 = new javax.swing.JButton();
        LebanonLeave1 = new javax.swing.JButton();
        NewLondon1 = new javax.swing.JButton();
        SouthLeave1 = new javax.swing.JButton();
        LoganLeave1 = new javax.swing.JButton();
        NYCLeave1 = new javax.swing.JButton();
        LeavingFrom3 = new javax.swing.JLabel();
        DestNotSet = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        SelectDest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Submit2 = new javax.swing.JButton();
        LeavingFrom = new javax.swing.JLabel();
        HanoverLeave = new javax.swing.JButton();
        SouthDest = new javax.swing.JButton();
        LoganDest = new javax.swing.JButton();
        NYCDest = new javax.swing.JButton();
        LeavingFrom1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        OneWay = new javax.swing.JButton();
        RoundTrip = new javax.swing.JButton();

        ChangeDept.setBounds(new java.awt.Rectangle(100, 100, 400, 500));

        LeavingFrom2.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        LeavingFrom2.setText("LOCATION");

        HanoverLeave1.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        HanoverLeave1.setText("HANOVER");
        HanoverLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HanoverLeave1ActionPerformed(evt);
            }
        });

        LebanonLeave1.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        LebanonLeave1.setText("LEBANON");
        LebanonLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebanonLeave1ActionPerformed(evt);
            }
        });

        NewLondon1.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NewLondon1.setText("NEW LONDON");
        NewLondon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLondon1ActionPerformed(evt);
            }
        });

        SouthLeave1.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        SouthLeave1.setText("BOSTON: SOUTH STATION");
        SouthLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthLeave1ActionPerformed(evt);
            }
        });

        LoganLeave1.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        LoganLeave1.setText("BOSTON: LOGAN AIRPORT");
        LoganLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoganLeave1ActionPerformed(evt);
            }
        });

        NYCLeave1.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NYCLeave1.setText("NEW YORK CITY");
        NYCLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NYCLeave1ActionPerformed(evt);
            }
        });

        LeavingFrom3.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        LeavingFrom3.setText("CHANGE DEPARTURE");

        javax.swing.GroupLayout ChangeDeptLayout = new javax.swing.GroupLayout(ChangeDept.getContentPane());
        ChangeDept.getContentPane().setLayout(ChangeDeptLayout);
        ChangeDeptLayout.setHorizontalGroup(
            ChangeDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangeDeptLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LeavingFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangeDeptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ChangeDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangeDeptLayout.createSequentialGroup()
                        .addGroup(ChangeDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HanoverLeave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SouthLeave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LebanonLeave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoganLeave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NYCLeave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewLondon1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangeDeptLayout.createSequentialGroup()
                        .addComponent(LeavingFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
        );
        ChangeDeptLayout.setVerticalGroup(
            ChangeDeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangeDeptLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(LeavingFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeavingFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HanoverLeave1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LebanonLeave1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewLondon1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SouthLeave1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoganLeave1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NYCLeave1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        DestNotSet.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        DestNotSet.setBounds(new java.awt.Rectangle(100, 200, 400, 180));

        jLabel2.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("You did not select a destination.");

        SelectDest.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        SelectDest.setText("SELECT A DESTINATION");
        SelectDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectDestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please select a destination to continue.");

        javax.swing.GroupLayout DestNotSetLayout = new javax.swing.GroupLayout(DestNotSet.getContentPane());
        DestNotSet.getContentPane().setLayout(DestNotSetLayout);
        DestNotSetLayout.setHorizontalGroup(
            DestNotSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestNotSetLayout.createSequentialGroup()
                .addGroup(DestNotSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DestNotSetLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(DestNotSetLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(SelectDest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DestNotSetLayout.setVerticalGroup(
            DestNotSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestNotSetLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectDest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Submit2.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Submit2.setText("SUBMIT");
        Submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2ActionPerformed(evt);
            }
        });

        LeavingFrom.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        LeavingFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeavingFrom.setText("LEAVING FROM:");

        HanoverLeave.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        HanoverLeave.setText("HANOVER");
        HanoverLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HanoverLeaveActionPerformed(evt);
            }
        });

        SouthDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        SouthDest.setText("BOSTON: SOUTH STATION");
        SouthDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthDestActionPerformed(evt);
            }
        });

        LoganDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        LoganDest.setText("BOSTON: LOGAN AIRPORT");
        LoganDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoganDestActionPerformed(evt);
            }
        });

        NYCDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        NYCDest.setText("NEW YORK CITY");
        NYCDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NYCDestActionPerformed(evt);
            }
        });

        LeavingFrom1.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        LeavingFrom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeavingFrom1.setText("GOING TO:");

        Back.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        OneWay.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        OneWay.setText("ONE WAY");
        OneWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneWayActionPerformed(evt);
            }
        });

        RoundTrip.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        RoundTrip.setText("ROUND TRIP");
        RoundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundTripActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(OneWay, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(RoundTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LoganDest, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(NYCDest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(LeavingFrom1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(LeavingFrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(HanoverLeave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(SouthDest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OneWay, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoundTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LeavingFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HanoverLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LeavingFrom1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SouthDest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoganDest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NYCDest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        TicketInfo ticketScreen = new TicketInfo(p);
        ticketScreen.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void HanoverLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HanoverLeaveActionPerformed
        ChangeDept.setVisible(true);
    }//GEN-LAST:event_HanoverLeaveActionPerformed

    private void HanoverLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HanoverLeave1ActionPerformed
        dept = "HANOVER";
        r.setDept(dept);
        ChangeDept.dispose();
        dispose();
        HanLebNLTicketInfo ticketform = new HanLebNLTicketInfo(r, p);
        ticketform.setVisible(true);
    }//GEN-LAST:event_HanoverLeave1ActionPerformed

    private void LebanonLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebanonLeave1ActionPerformed
        dept = "LEBANON";
        r.setDept(dept);
        ChangeDept.dispose();
        dispose();
        HanLebNLTicketInfo ticketform = new HanLebNLTicketInfo(r, p);
        ticketform.setVisible(true);
    }//GEN-LAST:event_LebanonLeave1ActionPerformed

    private void NewLondon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewLondon1ActionPerformed
        dept = "NEW LONDON";
        r.setDept(dept);
        ChangeDept.dispose();
        dispose();
        HanLebNLTicketInfo ticketform = new HanLebNLTicketInfo(r, p);
        ticketform.setVisible(true);
    }//GEN-LAST:event_NewLondon1ActionPerformed

    private void SouthLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthLeave1ActionPerformed
        dept = "BOSTON: SOUTH STATION";
        r.setDept(dept);
        ChangeDept.dispose();
        dispose();
        BosNYTicketInfo ticketform = new BosNYTicketInfo(r, p);
        ticketform.setVisible(true);
    }//GEN-LAST:event_SouthLeave1ActionPerformed

    private void LoganLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoganLeave1ActionPerformed
        dept = "BOSTON: LOGAN AIRPORT";
        r.setDept(dept);
        ChangeDept.dispose();
        dispose();
        BosNYTicketInfo ticketform = new BosNYTicketInfo(r, p);
        ticketform.setVisible(true);
    }//GEN-LAST:event_LoganLeave1ActionPerformed

    private void NYCLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NYCLeave1ActionPerformed
        dept = "NEW YORK CITY";
        r.setDept(dept);
        ChangeDept.dispose();
        dispose();
        BosNYTicketInfo ticketform = new BosNYTicketInfo(r, p);
        ticketform.setVisible(true);
    }//GEN-LAST:event_NYCLeave1ActionPerformed

    private void OneWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneWayActionPerformed
        isOneWay = true;
        r.setIsOneWay(isOneWay);
        RoundTrip.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        OneWay.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
    }//GEN-LAST:event_OneWayActionPerformed

    private void RoundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundTripActionPerformed
        isOneWay = false;
        r.setIsOneWay(isOneWay);
        OneWay.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        RoundTrip.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
    }//GEN-LAST:event_RoundTripActionPerformed

    private void SouthDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthDestActionPerformed
        dest = "BOSTON: SOUTH STATION";
        r.setDest(dest);
        destSet = true;
        SouthDest.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
        LoganDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        NYCDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
    }//GEN-LAST:event_SouthDestActionPerformed

    private void LoganDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoganDestActionPerformed
        dest = "BOSTON: LOGAN AIRPORT";
        r.setDest(dest);
        destSet = true;
        SouthDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        LoganDest.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
        NYCDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
    }//GEN-LAST:event_LoganDestActionPerformed

    private void NYCDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NYCDestActionPerformed
        dest = "NEW YORK CITY";
        r.setDest(dest);
        destSet = true;
        SouthDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        LoganDest.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        NYCDest.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
    }//GEN-LAST:event_NYCDestActionPerformed

    private void Submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2ActionPerformed
        if (!destSet) {
            DestNotSet.setVisible(true);
        }
        else {
            dispose();
            if (!isOneWay && (dest.equals("NEW YORK CITY") || dept.equals("NEW YORK CITY"))) {
                FinalizeTicketInfoNYC ticketformNYC = new FinalizeTicketInfoNYC(r, p);
                ticketformNYC.setVisible(true);
            }
            else {
                FinalizeTicketInfo ticketform = new FinalizeTicketInfo(r, p);
                ticketform.setVisible(true);
            }
        }
    }//GEN-LAST:event_Submit2ActionPerformed

    private void SelectDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectDestActionPerformed
        DestNotSet.dispose();
    }//GEN-LAST:event_SelectDestActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HanLebNLTicketInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HanLebNLTicketInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HanLebNLTicketInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HanLebNLTicketInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HanLebNLTicketInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JFrame ChangeDept;
    private javax.swing.JFrame DestNotSet;
    private javax.swing.JButton HanoverLeave;
    private javax.swing.JButton HanoverLeave1;
    private javax.swing.JLabel LeavingFrom;
    private javax.swing.JLabel LeavingFrom1;
    private javax.swing.JLabel LeavingFrom2;
    private javax.swing.JLabel LeavingFrom3;
    private javax.swing.JButton LebanonLeave1;
    private javax.swing.JButton LoganDest;
    private javax.swing.JButton LoganLeave1;
    private javax.swing.JButton NYCDest;
    private javax.swing.JButton NYCLeave1;
    private javax.swing.JButton NewLondon1;
    private javax.swing.JButton OneWay;
    private javax.swing.JButton RoundTrip;
    private javax.swing.JButton SelectDest;
    private javax.swing.JButton SouthDest;
    private javax.swing.JButton SouthLeave1;
    private javax.swing.JButton Submit2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
