/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs67proj;

import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kernst
 */
public class PaymentSuccess extends javax.swing.JFrame {

    private Reservation r;
    private Person p;
    private boolean receipt;
    private boolean credit;
    private double price;
    private int passengers;
    public final DecimalFormat df = new DecimalFormat("#.00");
    private boolean receiptSet;
    
    /**
     * Creates new form PaymentSuccess
     */
    public PaymentSuccess() {
        initComponents();
    }
    
    public PaymentSuccess(Reservation r, Person p, double price, boolean credit) {
        this.r = r;
        this.p = p;
        this.credit = credit;
        initComponents();
        if (!credit)
            CreditCardNum.setText("");
        this.price = price;
        Total.setText("$" + df.format(price));
        this.passengers = r.getAdults() + r.getKids();
        receiptSet = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoReceiptSet = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        SetReceipt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CreditCardNum = new javax.swing.JLabel();
        Success = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Submit2 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Receipt = new javax.swing.JLabel();
        Yes = new javax.swing.JButton();
        No = new javax.swing.JButton();
        Payment = new javax.swing.JLabel();

        NoReceiptSet.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        NoReceiptSet.setBounds(new java.awt.Rectangle(100, 200, 400, 180));

        jLabel8.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("You did not select whether or not to print a receipt.");

        SetReceipt.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        SetReceipt.setText("SELECT RECEIPT PREFERENCES");
        SetReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetReceiptActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Please select \"YES\" or \"NO\" to continue.");

        javax.swing.GroupLayout NoReceiptSetLayout = new javax.swing.GroupLayout(NoReceiptSet.getContentPane());
        NoReceiptSet.getContentPane().setLayout(NoReceiptSetLayout);
        NoReceiptSetLayout.setHorizontalGroup(
            NoReceiptSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoReceiptSetLayout.createSequentialGroup()
                .addGroup(NoReceiptSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(NoReceiptSetLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(SetReceipt)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        NoReceiptSetLayout.setVerticalGroup(
            NoReceiptSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoReceiptSetLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SetReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreditCardNum.setFont(new java.awt.Font("Avenir Next Condensed", 2, 24)); // NOI18N
        CreditCardNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreditCardNum.setText("was charged to your Discover card (**** **** **** 5892)");

        Success.setFont(new java.awt.Font("Avenir Next Condensed", 1, 80)); // NOI18N
        Success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Success.setText("SUCCESSFUL");

        Total.setFont(new java.awt.Font("Avenir Next Condensed", 0, 60)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("$00.00");

        Submit2.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Submit2.setText("SUBMIT & PRINT DOCUMENTS");
        Submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2ActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Receipt.setFont(new java.awt.Font("Avenir Next Condensed", 1, 40)); // NOI18N
        Receipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Receipt.setText("Would you like a receipt?");

        Yes.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Yes.setText("YES");
        Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesActionPerformed(evt);
            }
        });

        No.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        No.setText("NO");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });

        Payment.setFont(new java.awt.Font("Avenir Next Condensed", 1, 60)); // NOI18N
        Payment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Payment.setText("PAYMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit2)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Success, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreditCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Receipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(No, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Payment, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Success, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreditCardNum)
                .addGap(55, 55, 55)
                .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Yes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2ActionPerformed
        if (!receiptSet) {
            NoReceiptSet.setVisible(true);
        }
        else {
            dispose();
            PrintingDocs ticketFormPrint = new PrintingDocs(r, p, receipt, credit, price);
            ticketFormPrint.setVisible(true);
        }
    }//GEN-LAST:event_Submit2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
        if (credit) {
            CreditCardSwipe creditSwipeScreen = new CreditCardSwipe(r, p, price);
            creditSwipeScreen.setVisible(true);
        }
        else {
            CashPayment cashScreen = new CashPayment(r, p, price);
            cashScreen.setVisible(true);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed
        receipt = true;
        receiptSet = true;
        No.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
        Yes.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
    }//GEN-LAST:event_YesActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        receipt = false;
        receiptSet = true;
        No.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24));
        Yes.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24));
    }//GEN-LAST:event_NoActionPerformed

    private void SetReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetReceiptActionPerformed
        NoReceiptSet.dispose();
    }//GEN-LAST:event_SetReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentSuccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel CreditCardNum;
    private javax.swing.JButton No;
    private javax.swing.JFrame NoReceiptSet;
    private javax.swing.JLabel Payment;
    private javax.swing.JLabel Receipt;
    private javax.swing.JButton SetReceipt;
    private javax.swing.JButton Submit2;
    private javax.swing.JLabel Success;
    private javax.swing.JLabel Total;
    private javax.swing.JButton Yes;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
