/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs67proj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.Format;
import java.text.SimpleDateFormat;

/**
 *
 * @author laurenmitchell
 */
public class TicketSelected extends javax.swing.JFrame {
    public String nameLabel;
    public String birthDateLabel;
    private Ticket t;
    private Person p;
    public final Format formatter = new SimpleDateFormat("MM/dd/yyyy");
    
    /**
     * Creates new form TicketSelected
     */
    public TicketSelected(Person p, Ticket t) {
        this.t = t;
        this.p = p;
        if (p.getMiddle().length() == 0)
            this.nameLabel = "Name: " + p.getFirst() + " " + p.getLast();
        else {
            this.nameLabel = "Name: " + p.getFirst() + " " + p.getMiddle() +
                    ". " + p.getLast();
        }
        
        String bDay = formatter.format(p.getBirthDate());
        this.birthDateLabel = "Date of Birth: " + bDay;
        
        initComponents();
        Name.setText(nameLabel);
        BirthDate.setText(birthDateLabel);
        
        FakeEmployeeID.addActionListener(new ActionListener()
        {
        	  public void actionPerformed(ActionEvent e)
        	  {

                      try {
                        TimeUnit.SECONDS.sleep((long)0.3);
                      } catch (InterruptedException ex) {
                          Logger.getLogger(TicketSelected.class.getName()).log(Level.SEVERE, null, ex);
                      }
                        dispose();
                      PrintScreen eng = new PrintScreen(p, t);
                      eng.setVisible(true);
        	  }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BirthDate = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Directions = new javax.swing.JLabel();
        FakeEmployeeID = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Directions1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BirthDate.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        BirthDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BirthDate.setText("DATE OF BIRTH: 12/17/1995");

        Name.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("NAME: KENDALL A. ERNST");

        Directions.setFont(new java.awt.Font("Avenir Next Condensed", 2, 36)); // NOI18N
        Directions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Directions.setText("Please hand this device & a valid");

        FakeEmployeeID.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        FakeEmployeeID.setText("FAKE SWIPE EMPLOYEE ID");

        Back.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Directions1.setFont(new java.awt.Font("Avenir Next Condensed", 2, 36)); // NOI18N
        Directions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Directions1.setText("photo ID to the Coach Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Directions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Directions1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FakeEmployeeID)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(Directions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Directions1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FakeEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
       try {
            TimeUnit.SECONDS.sleep((long)0.3);
        } catch (InterruptedException ex) {
            Logger.getLogger(TicketSelected.class.getName()).log(Level.SEVERE, null, ex);
        }   
          
        dispose();
        TicketHistory eng = new TicketHistory(p);
        eng.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TicketSelected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TicketSelected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TicketSelected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TicketSelected.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TicketSelected().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel BirthDate;
    private javax.swing.JLabel Directions;
    private javax.swing.JLabel Directions1;
    private javax.swing.JButton FakeEmployeeID;
    private javax.swing.JLabel Name;
    // End of variables declaration//GEN-END:variables
}
