/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs67proj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author laurenmitchell
 */
public class TicketHistory extends javax.swing.JFrame {
    public static ArrayList<Ticket> tickets;
    public static int indexSelected;
    final DefaultListModel model = new DefaultListModel();
    public static Ticket ticketSelected;
    Person p;
    private boolean noEntries;
    /**
     * Creates new form TicketHistory
     */
    public TicketHistory(Person p) {
        this.p = p;
        tickets = null;
        this.noEntries = true;
        if (p == null)
            model.addElement("Sorry there are no tickets with that last name");
        else {
            tickets = p.getAllTickets();
            if (tickets == null) {
                model.addElement("Sorry there are no tickets with that last name");
            }
            else if (tickets.isEmpty()) {
                model.addElement("Sorry there are no tickets with that last name");
            }
            else {
                noEntries = false;
            }
        }
            
        indexSelected = -1;
        ticketSelected = null;
        initComponents();
        
        Submit.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e){
                if(TicketBox.getSelectedIndex() >= 0 && !noEntries){
                    indexSelected = TicketBox.getSelectedIndex();
                    ticketSelected = tickets.get(indexSelected);
                         
                    try {
                        TimeUnit.SECONDS.sleep((long)0.3);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TicketHistory.class.getName()).log(Level.SEVERE, null, ex);
                    }
                  
                    dispose();
                    TicketSelected eng = new TicketSelected(p, ticketSelected);
                    eng.setVisible(true);
                }
                else{
                    NoneSelected.setVisible(true);
                }
            }
        });
    }
    
    public DefaultListModel getJModel() {
   
        if (!p.getAllTickets().isEmpty()) {
            for (Ticket t : tickets){
                model.addElement(t.getLocation());
            }
        }
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoneSelected = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        SelectName = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PurchaseNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TicketBox = new javax.swing.JList<>();
        Title = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        NoneSelected.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        NoneSelected.setBounds(new java.awt.Rectangle(100, 200, 400, 270));

        jLabel3.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("You did not select a ticket from the list.");

        SelectName.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        SelectName.setText("SELECT A TICKET");
        SelectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please select a ticket from the list to continue.");

        jLabel5.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Alternatively, click below to purchase a new ticket.");

        PurchaseNew.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        PurchaseNew.setText("PURCHASE A NEW TICKET");
        PurchaseNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NoneSelectedLayout = new javax.swing.GroupLayout(NoneSelected.getContentPane());
        NoneSelected.getContentPane().setLayout(NoneSelectedLayout);
        NoneSelectedLayout.setHorizontalGroup(
            NoneSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoneSelectedLayout.createSequentialGroup()
                .addGroup(NoneSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NoneSelectedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(NoneSelectedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoneSelectedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PurchaseNew)
                .addGap(88, 88, 88))
            .addGroup(NoneSelectedLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(SelectName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NoneSelectedLayout.setVerticalGroup(
            NoneSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoneSelectedLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PurchaseNew, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TicketBox.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        TicketBox.setModel(this.getJModel());
        TicketBox.setToolTipText("");
        jScrollPane1.setViewportView(TicketBox);

        Title.setFont(new java.awt.Font("Avenir Next Condensed", 1, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("SELECT A TICKET TO PRINT");

        Submit.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Avenir Next Condensed", 0, 24)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        try {
            TimeUnit.SECONDS.sleep((long)0.3);
            } catch (InterruptedException ex) {
                Logger.getLogger(TicketHistory.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
        NameHistory eng = new NameHistory(p.getLast());
        eng.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void SelectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectNameActionPerformed
        NoneSelected.dispose();
    }//GEN-LAST:event_SelectNameActionPerformed

    private void PurchaseNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseNewActionPerformed
        NoneSelected.dispose();
        dispose();
        PurchaseFullName purchWindow = new PurchaseFullName();
        purchWindow.setVisible(true);
    }//GEN-LAST:event_PurchaseNewActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TicketHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TicketHistory().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JFrame NoneSelected;
    private javax.swing.JButton PurchaseNew;
    private javax.swing.JButton SelectName;
    private javax.swing.JButton Submit;
    private javax.swing.JList<String> TicketBox;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
